services:
  reverse-proxy:
    image: caddy
    container_name: "caddy"
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./caddy_data:/data"
      - "./caddy_config:/config"
      - "./Caddyfile:/etc/caddy/Caddyfile"  
  haven-web:
    image: ghcr.io/armchairancap/haven:latest
    container_name: "haven-web"
    entrypoint: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - tor
    networks:
      - tor_network
  tor:
    image: alpine:latest
    command: sh -c "apk update && apk add tor && chmod 700 /var/lib/tor/hidden_service && (cat /var/lib/tor/hidden_service/hostname || echo 'Hostname not available.') && tor -f /etc/tor/torrc"
    volumes:
      - ./tor-config:/etc/tor:rw
      - ./tor-service:/var/lib/tor/hidden_service:rw
    networks:
      - tor_network
    stop_grace_period: 1m
  s3-server:
    image: minio/minio:latest
    container_name: "s3-server"
    command: server --address "127.0.0.1:59000" --console-address "127.0.0.1:59001" /data
    ports:
      - "59000:59000"
      - "59001:59001"
    volumes:
      - ./tor-docs:/data
    environment: 
      MINIO_ROOT_USER: 
      MINIO_ROOT_PASSWORD: 
      MINIO_SERVER_URL: "https://localhost:59001"
    depends_on:
      - tor
    networks:
      - tor_network
networks:
  tor_network:
